FROM debian:bullseye-20210208

RUN apt update && \
    apt install -y -q build-essential libncurses-dev bison flex libssl-dev libelf-dev dwarves

RUN apt install -y -q bc sudo
RUN apt install -y -q cpio
RUN apt install -y -q python3
RUN apt install -y -q autoconf automake binutils
RUN apt install -y -q kmod

RUN groupadd -g 1002 -o guodong
RUN useradd -u 1001 -g 1002 -G sudo -ms /bin/bash guodong
RUN echo "guodong:guodong" | chpasswd

USER guodong
CMD ["bash"]
