FROM ubuntu:22.04
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y apt-utils

RUN apt-get -y -q install autoconf automake libtool numactl \
	   gcc automake autoconf libtool make git \
	   pkg-config libnuma-dev \
	   build-essential cmake \
	   sudo

RUN apt-get -y -q install python2 python3
RUN apt-get -y -q install zlib1g-dev
RUN apt-get install -y -q libncurses-dev bison flex \
	 libssl-dev libelf-dev dwarves

RUN apt-get install -y -q bc sudo
RUN apt-get install -y -q cpio
RUN apt-get install -y -q binutils
RUN apt-get install -y -q kmod vim git
RUN apt-get install -y -q man-db manpages-dev

# Test 2 framework Perl
RUN apt-get install -y -q perl cpanminus
RUN cpanm Test2
RUN cpanm Test2::V0

# handy tools
RUN apt-get install -y -q tree htop

# nasm, General-purpose x86 assembler
RUN apt-get install -y -q nasm

# rsyslog service, required by UADK logs
RUN apt-get install -y -q rsyslog

################################
# JDK development requirement
################################
RUN apt-get install -y -q unzip zip jtreg
RUN apt-get install -y -q libx11-dev libxext-dev libxrender-dev libxtst-dev libxt-dev
RUN apt-get install -y -q libcups2-dev
RUN apt-get install -y -q libfreetype6-dev
RUN apt-get install -y -q libasound2-dev
RUN apt-get install -y -q libfontconfig1-dev
RUN apt-get install -y -q gawk wget

################################
# create a user account
################################
# add new user: guodong, with sudo previlidge
RUN groupadd -g 1000 -o guodong
RUN useradd -u 1000 -g 1000 -G sudo -ms /bin/bash guodong
RUN echo "guodong:guodong" | chpasswd

USER guodong

############################################
# Install UADK environment setting script
############################################
COPY ./metadata/uadk-set-env.sh /home/guodong

CMD ["bash"]
